name: selenium

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1,21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
    #  - name: 'Set up Python'
    #    uses: actions/setup-python@v1
    #    with:
    #      python-version: 3.7
    #  - name: 'Install requirements'
    #    run: pip install -r ./Spider/requirements.txt
    #  - name: 'Working'
    #    run: |
    #      sudo cp -p ./chrome/chromedriver /usr/bin/
    #      chmod -R 777 /usr/bin/chromedriver
    #      python ./Spider/test.py
      - name: 'Current time'
        id: ct
        uses: Kaven-Universe/github-action-current-date-time@v1.1.0
        with:
          format: "YYYY年MM月DD日 HH:mm:ss"
          timezone-offset: -480
      - name: 'Current time output'
        run: |
          echo "The time was ${{ steps.ct.outputs.time }}"
    
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
           server_address: smtp.126.com
           server_port: 465
           username: ${{ secrets.MAILUSERNAME }}
           password: ${{ secrets.MAILPASSWORD }}
           subject: JiaoYi Report
           body: ${{ steps.ct.outputs.time }} JiaoYi DaCheng, No Neigui!
           to: ${{ secrets.TO }}
           from: JiJiGuoWang
           content_type: text/plain
